#pragma once
#include "ObjExporter.h"
#include <fstream>

extern "C" __declspec(dllexport) void SaveModel(LoadedModel* model, std::string filepath)
{
	std::ofstream objFile;
	objFile.open(filepath);
	std::ofstream mtlFile;
	std::string mtlPath = filepath.substr(0, filepath.length() - 3) + "mtl";
	mtlFile.open(mtlPath);
	if (!objFile.is_open()) return;
	if (!mtlFile.is_open()) return;
	objFile << "#### AUTOGENERATED BY OBJ DLL ####\n";
	objFile << "mtllib " << mtlPath << "\n";
	mtlFile << "#### AUTOGENERATED BY OBJ DLL ####\n";
	std::vector<std::string> parsedMats = std::vector<std::string>();
	int offset = 0;
	for (int i = 0; i < model->modelParts.size(); i++) {
		//OBJ
		objFile << "o part_" << std::to_string(i) << "\n";
		for (int x = 0; x < model->modelParts[i].compVertices.size(); x++) {
			Vector3 thisVert = model->modelParts[i].compVertices[x].Pos;
			objFile << "v " << std::to_string(thisVert.x) << " " << std::to_string(thisVert.y) << " " << std::to_string(thisVert.z) << "\n";
		}
		for (int x = 0; x < model->modelParts[i].compVertices.size(); x++) {
			Vector2 thisCoord = model->modelParts[i].compVertices[x].Tex;
			objFile << "vt " << std::to_string(thisCoord.x) << " " << std::to_string(thisCoord.y * -1) << "\n";
		}
		for (int x = 0; x < model->modelParts[i].compVertices.size(); x++) {
			Vector3 thisNorm = model->modelParts[i].compVertices[x].Normal;
			objFile << "vn " << std::to_string(thisNorm.x) << " " << std::to_string(thisNorm.y) << " " << std::to_string(thisNorm.z) << "\n";
		}
		objFile << "usemtl " << model->modelParts[i].materialName << "\n";
		for (int x = 0; x < model->modelParts[i].compIndices.size(); x += 3) {
			objFile << "f " << model->modelParts[i].compIndices[x] + 1 + offset << "/" << model->modelParts[i].compIndices[x] + 1 + offset << "/" << model->modelParts[i].compIndices[x] + 1 + offset << " ";
			objFile << model->modelParts[i].compIndices[x + 1] + 1 + offset << "/" << model->modelParts[i].compIndices[x + 1] + 1 + offset << "/" << model->modelParts[i].compIndices[x + 1] + 1 + offset << " ";
			objFile << model->modelParts[i].compIndices[x + 2] + 1 + offset << "/" << model->modelParts[i].compIndices[x + 2] + 1 + offset << "/" << model->modelParts[i].compIndices[x + 2] + 1 + offset << "\n";
		}
		offset += model->modelParts[i].compIndices[model->modelParts[i].compIndices.size() - 1] + 1;

		//MTL
		bool alreadyExported = false;
		for (int x = 0; x < parsedMats.size(); x++) {
			if (parsedMats[x] == model->modelParts[i].materialName) {
				alreadyExported = true;
				break;
			}
		}
		if (alreadyExported) continue;
		parsedMats.push_back(model->modelParts[i].materialName);
		mtlFile << "\nnewmtl " << model->modelParts[i].materialName << "\n";
		//mtlFile << "Kd " << model->modelParts[i].thisMaterial.r << " " << model->modelParts[i].thisMaterial.g << " " << model->modelParts[i].thisMaterial.b << "\n";
		//mtlFile << "d " << model->modelParts[i].thisMaterial.a << "\n";
		mtlFile << "map_Kd " << model->modelParts[i].materialName << ".dds\n";
		mtlFile << "illum 2\n";
	}
	objFile.close();
	mtlFile.close();
}
