//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaterialEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture2D txDiffuse : register( t0 );
        ///SamplerState samLinear : register( s0 );
        ///
        ///cbuffer ConstantBuffer : register( b0 )
        ///{
        ///	matrix World;
        ///	matrix View;
        ///	matrix Projection;
        ///%CUSTOM_PARAMS%
        ///}
        ///
        ///struct VS_INPUT
        ///{
        ///    float4 Pos : POSITION;
        ///    float2 Tex : TEXCOORD0;
        ///    float3 Norm : NORMAL;
        ///};
        ///
        ///struct PS_INPUT
        ///{
        ///    float4 Pos : SV_POSITION;
        ///    float4 WorldPos : POSITION;
        ///    float2 Tex : TEXCOORD0;
        ///    float3 Norm : NORMAL;
        ///};
        ///
        ///PS_INPUT VS( VS_INPUT input )
        ///{
        ///    PS_INPUT output = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string shader_template {
            get {
                return ResourceManager.GetString("shader_template", resourceCulture);
            }
        }
    }
}
